# Generated by Django 4.2.4 on 2024-02-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("cat_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.IntegerField()),
                ("comp_id", models.IntegerField()),
                ("amount_need", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Devices",
            fields=[
                ("device_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("device_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.CreateModel(
            name="OrderData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(max_length=255)),
                ("in_stock", models.IntegerField()),
                ("amount_need", models.IntegerField()),
                ("cat", models.IntegerField()),
                ("enough", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Replace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_name", models.CharField(max_length=255)),
                ("cat", models.IntegerField()),
                ("in_stock", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Components",
            fields=[
                ("comp_id", models.AutoField(primary_key=True, serialize=False)),
                ("comp_name", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="components.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Component",
                "verbose_name_plural": "Components",
            },
        ),
    ]
